# Generated by Django 6.0.2 on 2026-02-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskaccounts',
            old_name='balance',
            new_name='gold_balance',
        ),
        migrations.AddField(
            model_name='taskaccounts',
            name='silver_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
